      MODULE compfg_I   
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.4G  09:47:13  03/15/06  
      SUBROUTINE compfg (XPARAM, INT, ESCF, FULSCF, GRAD, LGRAD) BIND(C)
      USE, INTRINSIC :: iso_c_binding, only: C_DOUBLE, C_BOOL
      REAL(C_DOUBLE), DIMENSION(*), intent (in) :: XPARAM 
      logical(C_BOOL), intent(in) :: INT, fulscf 
      REAL(C_DOUBLE), intent(out) :: ESCF 
      REAL(C_DOUBLE), DIMENSION(*) :: GRAD 
      LOGICAL(C_BOOL), intent(in) :: LGRAD 
      END SUBROUTINE  
      END INTERFACE 
      END MODULE 
